Update Testing.md
installing the red color and installation instruction for coverage which breaks the test on the first step

```
Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/usr/local/lib/python3.8/dist-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python3.8/dist-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/usr/local/lib/python3.8/dist-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/usr/local/lib/python3.8/dist-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/usr/local/lib/python3.8/dist-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/local/lib/python3.8/dist-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/usr/local/lib/python3.8/dist-packages/nose/plugins/cover.py", line 155, in configure
    self.coverInstance.load()
  File "/usr/local/lib/python3.8/dist-packages/coverage/control.py", line 426, in load
    self._data.read()
  File "/usr/local/lib/python3.8/dist-packages/coverage/sqldata.py", line 753, in read
    with self._connect():       # TODO: doesn't look right
  File "/usr/local/lib/python3.8/dist-packages/coverage/sqldata.py", line 300, in _connect
    self._create_db()
  File "/usr/local/lib/python3.8/dist-packages/coverage/sqldata.py", line 249, in _create_db
    with db:
  File "/usr/local/lib/python3.8/dist-packages/coverage/sqldata.py", line 1037, in __enter__
    self._connect()
  File "/usr/local/lib/python3.8/dist-packages/coverage/sqldata.py", line 1019, in _connect
    self.con = sqlite3.connect(filename, check_same_thread=False)
sqlite3.OperationalError: unable to open database file
```